name: ims_pos_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2+1
  sqflite_common_ffi: ^2.4.0
  path: ^1.9.1
  crypto: ^3.0.7
  pdf: ^3.10.0
  file_picker: ^6.0.0
  printing: ^5.11.0
  excel: ^4.0.6
  intl: ^0.19.0
  desktop_multi_window: ^0.3.0
  window_manager: ^0.5.1
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  
  # Add these lines for Desktop support:
  windows:
    generate: true
    image_path: "assets/icons/icon.png" # Path to your PNG
    icon_size: 256 # Default size for Windows ICO file
  macos:
    generate: true
    image_path: "assets/icons/icon.png" # Path to your PNG
  linux:
    generate: true
    image_path: "assets/icons/icon.png" # Path to your PNG